use super::*;

pub fn tile_gfx(terrain: chipty::Terrain) -> render::TileGfx {
	use chipty::{ModelId, SpriteId, Terrain};

	let (sprite, model) = match terrain {
		Terrain::Blank => (SpriteId::Blank, ModelId::Empty),
		Terrain::Floor => (SpriteId::Floor, ModelId::Floor),
		Terrain::Wall => (SpriteId::Wall, ModelId::Wall),
		Terrain::Socket => (SpriteId::Floor, ModelId::Floor),
		Terrain::BlueLock => (SpriteId::BlueLock, ModelId::Wall),
		Terrain::RedLock => (SpriteId::RedLock, ModelId::Wall),
		Terrain::GreenLock => (SpriteId::GreenLock, ModelId::Wall),
		Terrain::YellowLock => (SpriteId::YellowLock, ModelId::Wall),
		Terrain::Hint => (SpriteId::Hint, ModelId::Floor),
		Terrain::Exit => (SpriteId::ExitA, ModelId::EndPortal),
		Terrain::FakeExit => (SpriteId::ExitA, ModelId::EndPortal),
		Terrain::Water => (SpriteId::WaterA, ModelId::Floor),
		Terrain::WaterHazard => (SpriteId::WaterHazard, ModelId::Floor),
		Terrain::Fire => (SpriteId::Floor, ModelId::Floor),
		Terrain::Dirt => (SpriteId::Dirt, ModelId::Floor),
		Terrain::DirtBlock => (SpriteId::DirtBlock, ModelId::Wall),
		Terrain::Gravel => (SpriteId::Gravel, ModelId::Floor),
		Terrain::Ice => (SpriteId::Ice, ModelId::Floor),
		Terrain::IceNW => (SpriteId::IceCornerNW, ModelId::Floor),
		Terrain::IceNE => (SpriteId::IceCornerNE, ModelId::Floor),
		Terrain::IceSW => (SpriteId::IceCornerSW, ModelId::Floor),
		Terrain::IceSE => (SpriteId::IceCornerSE, ModelId::Floor),
		Terrain::ForceN => (SpriteId::ForceFloorNA, ModelId::Floor),
		Terrain::ForceW => (SpriteId::ForceFloorWA, ModelId::Floor),
		Terrain::ForceS => (SpriteId::ForceFloorSA, ModelId::Floor),
		Terrain::ForceE => (SpriteId::ForceFloorEA, ModelId::Floor),
		Terrain::ForceRandom => (SpriteId::ForceRandomA, ModelId::Floor),
		Terrain::CloneMachine => (SpriteId::CloneMachine, ModelId::Wall),
		Terrain::CloneBlockN => (SpriteId::CloneBlockN, ModelId::Wall),
		Terrain::CloneBlockW => (SpriteId::CloneBlockW, ModelId::Wall),
		Terrain::CloneBlockS => (SpriteId::CloneBlockS, ModelId::Wall),
		Terrain::CloneBlockE => (SpriteId::CloneBlockE, ModelId::Wall),
		Terrain::ToggleFloor => (SpriteId::ToggleFloorA, ModelId::Floor),
		Terrain::ToggleWall => (SpriteId::ToggleWallA, ModelId::Wall),
		Terrain::ThinWallN => (SpriteId::ThinWallN, ModelId::Floor),
		Terrain::ThinWallW => (SpriteId::ThinWallW, ModelId::Floor),
		Terrain::ThinWallS => (SpriteId::ThinWallS, ModelId::Floor),
		Terrain::ThinWallE => (SpriteId::ThinWallE, ModelId::Floor),
		Terrain::ThinWallNW => (SpriteId::ThinWallNW, ModelId::Floor),
		Terrain::ThinWallNE => (SpriteId::ThinWallNE, ModelId::Floor),
		Terrain::ThinWallSW => (SpriteId::ThinWallSW, ModelId::Floor),
		Terrain::ThinWallSE => (SpriteId::ThinWallSE, ModelId::Floor),
		Terrain::ThinWallH => (SpriteId::ThinWallH, ModelId::Floor),
		Terrain::ThinWallV => (SpriteId::ThinWallV, ModelId::Floor),
		Terrain::HiddenWall => (SpriteId::HiddenWall, ModelId::Wall),
		Terrain::InvisibleWall => (SpriteId::InvisibleWall, ModelId::Wall),
		Terrain::RealBlueWall => (SpriteId::RealBlueWall, ModelId::Wall),
		Terrain::FakeBlueWall => (SpriteId::FakeBlueWall, ModelId::Wall),
		Terrain::GreenButton => (SpriteId::GreenButton, ModelId::Floor),
		Terrain::RedButton => (SpriteId::RedButton, ModelId::Floor),
		Terrain::BrownButton => (SpriteId::BrownButton, ModelId::Floor),
		Terrain::BlueButton => (SpriteId::BlueButton, ModelId::Floor),
		Terrain::Teleport => (SpriteId::Teleport, ModelId::Floor),
		Terrain::BearTrap => (SpriteId::BearTrap, ModelId::Floor),
		Terrain::RecessedWall => (SpriteId::RecessedWall, ModelId::Floor),
	};

	render::TileGfx { sprite, model }
}
